{% set name = "xplot" %}
{% set version = "0.14.0" %}
{% set sha256 = "690781437b63ec6813f41c1813cbbc296dc155d69b5f57630c7a8c110023b61f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xplot/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xeus >=0.20.0,<0.21
    - xtl >=0.6.5,<0.7
    - xproperty >=0.8.1,<0.9
    - xwidgets >=0.18.0,<0.19

test:
  commands:
    - test -d ${PREFIX}/include/xplot  # [unix]
    - test -f ${PREFIX}/include/xplot/xmarks.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xplot/xplotConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xplot/xplotConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xplot\xmarks.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xplotConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xplotConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xplot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the bqplot 2-D plotting library'
  doc_url: http://xplot.readthedocs.io
  dev_url: https://github.com/QuantStack/xplot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
