appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VOY02v1Ju6ESfrl52hWYQYXf/kzmxgEXmO3T02HxQxe77QGRnt5q/xXblvyaLuge98Z0h0WjfapTVGZVBGU95VS9e0mR+xFPxKboKFUA4wqtVNk2kvY1Pv4TKI1XUwJS+utwCxu5NwC5393pCPw1RUtIkWwLyJ6HimRC5X/+lrUyoXtqPJ1kYX7x8Mmhna1m2M5A6RqrJY+OMJPOq88EF9nOIuwo//Ergp3BzxpupEkY/HPP0ONrkzKpQVCnecLbBp+c+Ir5jI3BTKfLDaVm6d4ZnUg1hZNOlV1SvUdkWQqhQNxse6amMMSyyOkEbSD/5naeoP2MZPO7aVXN2Cha6nF1zciCIOl0uVJKa2GvnNQTr2QclGqDv4XaqgR4TF5HZKMeo4slXeC/5UT+htmfQxukh76Z6bwcSzB/MYxxpKnQxARUKI0jsWJEeupeddGV1KDy9cK4Zb3YWYJcFMzOuyOOVC+F9oa7UwZ016mTiYNLRMkTtg6G346UDP3oJLdlMYFCCIlEk5m4uuVywpt05HfpPiQPeDUCPuxjGdYx08NSdk39LUTzIF5riEFb1eXyeDxih5ceh8JfMBe4gwwHJDIAxE8sdNkO8wqZyB/eng69wWe4f4DqlT85HqoTuAluGRo0h41iM3pONazsZZxmS3L+sYWdzdaGIbZC2uSIImg=}
provider:
  win: azure
conda_forge_output_validation: true
